### ISSUE TITLE
making PCHA compatible with python3

### ISSUE THREAD

**Issue by vitkl** [ulfaslak/py_pcha#3]
Hi Ulf,

I would like to know if you plan to make the code compatible with python3, or if not possible creating a python 3 version of the package. I am happy to contribute just want to know your plans to avoid duplication of effort. 
I am also surprised that one of the commits to furthest_sum module makes it compatible with python 3, but the py_pcha is not, which might indicate a potential compatibility issue.

**Comment by ulfaslak** [comment]
Thanks for raising the issue. You're welcome to make a pull request, otherwise I'll have a look at this soonish (have a PhD deadline in a couple months).

**Comment by vitkl** [comment]
I will probably do it earlier. I will get back to you with my pull request.

**Comment by dburkhardt** [comment]
+1 

I would like to see this

**Comment by ulfaslak** [comment]
@vitkl @dburkhardt Alright, fixed this, it should now work with Python 3 (at least it does here). New version is on PyPI so you can go ahead and

`pip install --upgrade py_pcha`

to get the newest version. Cheers! 🍻
