### ISSUE TITLE
should C matrix be of dimensions data points * archetypes?

### ISSUE THREAD

**Issue by vitkl** [ulfaslak/py_pcha#4]
Hi Ulf,

I was reading archetypal analysis paper by Mørup & Hansen, and realised that if the definition of the model is:
X = S * C * X 
than C should be of dimensions data points * archetypes.

However, in you implementation, it is of dimensions archetypes * archetypes, and in practice always contains 0s. In the Mørup & Hansen Matlab implementation it is data points * archetypes, so you probably have a bug in how C matrix is returned.

**Comment by ulfaslak** [comment]
I cannot reproduce this. Can you maybe send me some code to specify the case when this occurs.

If I run the example code from the README then I get exactly that the dimensions of C are datapoints * archetypes:

Example:
```Python
import numpy as np
import py_pcha

dimensions = 15
examples = 100
X = np.random.random((dimensions, examples))

XC, S, C, SSE, varexpl = py_pcha.PCHA(X, noc=3, delta=0.1)

print(C.shape)
C
```
Output:
```
(100, 3)
matrix([[0.        , 0.        , 0.        ],
        [0.        , 0.1282735 , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.01857616, 0.        ],
        [0.3038001 , 0.        , 0.        ],
        [0.        , 0.03852259, 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.08063509, 0.        ],
        [0.        , 0.        , 0.        ],
        ...
])
```

**Comment by vitkl** [comment]
Thanks a lot for checking! Sorry, my bad here. It was a bug in my code truncating the matrix after your code returned it correctly.
